# Generated by Django 5.2.12 on 2026-04-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=128)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
            ],
        ),
    ]
